// -----------------------------------------------------------------------------
// tb_main.cc -- CXXRTL testbench for rtl/frac_phase_scheduler.sv
//
// Built by rtl/run_sim.py:  yosys (read_verilog -sv -> write_cxxrtl simtop.cc)
// then  $CXX -std=c++14 -I<cxxrtl runtime> -I<build dir> tb_main.cc -o sim
//
// `simtop` (generated by run_sim.py) instantiates one frac_phase_scheduler per
// (F, LAT) variant on shared inputs and muxes their outputs with `sel`.
//
// usage: sim <sel> <fcw> <q_mode> <r_zero> <n_cycles>
//
// Two passes are run and dumped as CSV on stdout
// (pass,k,valid,n_int,m_fb,c_fb,r_fb,r_inj,j_inj,c_inj,seq_id):
//
//   pass 0  power-up -> 1-clock synchronous reset -> `en` held high (clk is
//           the reference clock).
//   pass 1  reset re-asserted MID-RUN with en = 1 on the same edge (reset
//           must win), then `en` is a sparse strobe with 0..3 idle clocks in
//           between (pseudo-random, fixed seed).  During idle clocks the
//           outputs must hold; a violation is reported as a line
//           "!unstable,<k>,<idle clock>".
//
// Row k is sampled after exactly k strobes since reset release, i.e. it is
// the command presented for reference cycle k.  The comparison against the
// golden vectors is done by run_sim.py.
// -----------------------------------------------------------------------------
#include <cstdint>
#include <cstdio>
#include <cstdlib>

#include <cxxrtl/cxxrtl.h>

#include "simtop.cc"

namespace {

struct Sample {
    uint32_t valid, n_int, m_fb, c_fb, r_fb, r_inj, j_inj, c_inj, seq_id;

    bool operator==(const Sample &o) const {
        return valid == o.valid && n_int == o.n_int && m_fb == o.m_fb &&
               c_fb == o.c_fb && r_fb == o.r_fb && r_inj == o.r_inj &&
               j_inj == o.j_inj && c_inj == o.c_inj && seq_id == o.seq_id;
    }
};

typedef cxxrtl_design::p_simtop Dut;

Sample sample(Dut &top) {
    Sample s;
    s.valid  = top.p_valid.get<uint32_t>();
    s.n_int  = top.p_nint.get<uint32_t>();
    s.m_fb   = top.p_mfb.get<uint32_t>();
    s.c_fb   = top.p_cfb.get<uint32_t>();
    s.r_fb   = top.p_rfb.get<uint32_t>();
    s.r_inj  = top.p_rinj.get<uint32_t>();
    s.j_inj  = top.p_jinj.get<uint32_t>();
    s.c_inj  = top.p_cinj.get<uint32_t>();
    s.seq_id = top.p_seqid.get<uint32_t>();
    return s;
}

// One full clock period.  Inputs are already set and clk is low: the rising
// edge clocks the flops, the falling-edge step() then re-evaluates the
// combinational logic downstream of the updated flops, so the outputs read
// after tick() belong to the new state (a single CXXRTL step() after the
// active edge leaves combinational outputs one delta behind).
void tick(Dut &top) {
    top.p_clk.set<bool>(true);
    top.step();
    top.p_clk.set<bool>(false);
    top.step();
}

// 16-bit Fibonacci LFSR (x^16 + x^14 + x^13 + x^11 + 1), fixed seed
uint32_t lfsr_next(uint32_t &state) {
    uint32_t bit = ((state >> 0) ^ (state >> 2) ^ (state >> 3) ^ (state >> 5)) & 1u;
    state = (state >> 1) | (bit << 15);
    return state;
}

}  // namespace

int main(int argc, char **argv) {
    if (argc != 6) {
        std::fprintf(stderr,
                     "usage: %s <sel> <fcw> <q_mode> <r_zero> <n_cycles>\n",
                     argv[0]);
        return 2;
    }
    const uint32_t sel      = static_cast<uint32_t>(std::strtoul(argv[1], nullptr, 0));
    const uint64_t fcw      = std::strtoull(argv[2], nullptr, 0);
    const uint32_t q_mode   = static_cast<uint32_t>(std::strtoul(argv[3], nullptr, 0));
    const uint32_t r_zero   = static_cast<uint32_t>(std::strtoul(argv[4], nullptr, 0));
    const long     n_cycles = std::strtol(argv[5], nullptr, 0);

    Dut top;

    // quasi-static configuration
    top.p_sel.set<uint32_t>(sel);
    top.p_fcw.set<uint64_t>(fcw);
    top.p_qmode.set<uint32_t>(q_mode);
    top.p_rzero.set<uint32_t>(r_zero);
    top.p_rst.set<bool>(false);
    top.p_en.set<bool>(false);
    top.p_clk.set<bool>(false);
    top.step();

    std::printf("pass,k,valid,n_int,m_fb,c_fb,r_fb,r_inj,j_inj,c_inj,seq_id\n");

    uint32_t lfsr = 0xACE1u;

    for (int pass = 0; pass < 2; ++pass) {
        // synchronous reset.  In pass 1 the state is dirty (mid-run) and en is
        // high on the reset edge: reset must take priority.
        top.p_rst.set<bool>(true);
        top.p_en.set<bool>(pass == 1);
        tick(top);
        top.p_rst.set<bool>(false);
        top.p_en.set<bool>(pass == 0);  // pass 0: en tied high
        top.step();

        for (long k = 0; k < n_cycles; ++k) {
            const Sample s = sample(top);
            std::printf("%d,%ld,%u,%u,%u,%u,%u,%u,%u,%u,%u\n", pass, k, s.valid,
                        s.n_int, s.m_fb, s.c_fb, s.r_fb, s.r_inj, s.j_inj,
                        s.c_inj, s.seq_id);

            if (pass == 1) {
                // idle clocks: en low, outputs must hold
                const uint32_t idle = lfsr_next(lfsr) & 3u;
                top.p_en.set<bool>(false);
                for (uint32_t i = 0; i < idle; ++i) {
                    tick(top);
                    if (!(sample(top) == s))
                        std::printf("!unstable,%ld,%u\n", k, i);
                }
                top.p_en.set<bool>(true);
            }
            tick(top);  // reference-cycle strobe k -> k+1
        }
    }
    return 0;
}
